import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/navbar";
import Footer from "./components/Footer/footer";
import Sidebar_R from "./components/Sidebar_R/sidebar_r";
import Sidebar_L from "./components/Sidebar_L/sidebar_L";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "پنل کاربری | اکس اونیکس",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
